[package]
name = "cw-ics721-bridge"
version = "0.0.1"
authors = ["ekez <ekez@withoutdoing.com>"]
edition = "2021"
description = "an implementation of the ICS721 specification for transfering NFTs between blockchains"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-std = { version = "1.1", features = ["stargate"] }
cosmwasm-schema = "1.1"
cw-storage-plus = "0.15"
cw-utils = "0.15"
cw2 = "0.15"
cw721 = "0.15"
cw721-base = { version = "0.15", features = ["library"] }
thiserror = "1"
serde = "1.0"
cw-paginate = { git = "https://github.com/DA0-DA0/dao-contracts.git" }
cw721-proxy-derive = { git = "https://github.com/ezekiiel/cw721-proxy.git" }
cw-pause-once = { path = "../../packages/cw-pause-once" }

[dev-dependencies]
cw-multi-test = "0.13.4"
